# Generated by Django 4.0.1 on 2022-01-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oder',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='oder_id',
            field=models.ManyToManyField(to='app.Oder'),
        ),
    ]
